[color-theme]
name = "Monokai"

[color-theme.base]
white = "#D6D6D6"
black = "#272822"
grey = "#75715E"
blue = "#6c99bb"
red = "#E06C75"
yellow = "#e5b567"
orange = "#e87d3e"
green = "#b4d273"
purple = "#9e86c8"
cyan = "#56B6C2"
magenta = "#b05279"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#272822"
"activity.current" = "$black"
"completion.background" = "#272822"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "$white"
"editor.current_line" = "#3e3d32"
"editor.dim" = "#5C6370"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#3e3d32"
"inlay_hint.background" = "#528abF37"
"inlay_hint.foreground" = "$white"
"lapce.border" = "#000000"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "$blue"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "#1e1f1c"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = ""
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#272822"
"palette.current.background" = "#1e1f1c"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#1e1f1c"
"panel.current.background" = "#75715E"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.hovered.background" = "#75715E"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#414339"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"
